# 総合型選抜関連キーワード（新規追加）
selection_types:
  - "総合型選抜"
  - "AO入試"
  - "総合選抜"
  - "特別選抜"
  - "総合型"
  - "AO"

quota_patterns:
  - "\\d+名"
  - "若干名"
  - "数名"
  - "\\d+名程度"
  - "\\d+人"
  - "若干人"

faculties:
  - "医学部"
  - "農学部"
  - "獣医学部"
  - "理学部"
  - "工学部"
  - "薬学部"
  - "歯学部"

selection_criteria:
  - "面接"
  - "小論文"
  - "プレゼンテーション"
  - "実技"
  - "グループディスカッション"
  - "志望理由書"
  - "活動実績"
