# 農学系免疫学キーワード（新規追加）
animal_immunity:
  - "動物免疫"
  - "veterinary immunology"
  - "家畜免疫"
  - "livestock immunity"
  - "魚類免疫"
  - "fish immunology"
  - "水産免疫"
  - "aquatic immunology"
  - "比較免疫学"
  - "comparative immunology"

animal_species:
  - "牛"
  - "cattle"
  - "bovine"
  - "豚"
  - "porcine"
  - "swine"
  - "鶏"
  - "chicken"
  - "poultry"
  - "魚"
  - "fish"
  - "犬"
  - "canine"
  - "猫"
  - "feline"
  - "馬"
  - "equine"
  - "羊"
  - "sheep"
  - "ovine"

plant_immunity:
  - "植物免疫"
  - "plant immunity"
  - "植物病理"
  - "plant pathology"
  - "植物防御"
  - "plant defense"
  - "病害抵抗性"
  - "disease resistance"
  - "植物ワクチン"
  - "plant vaccine"

food_immunity:
  - "食品免疫"
  - "food immunology"
  - "栄養免疫"
  - "nutritional immunology"
  - "機能性食品"
  - "functional food"
  - "プロバイオティクス"
  - "probiotics"
  - "発酵食品"
  - "fermented food"
  - "腸内細菌"
  - "gut microbiota"

veterinary_medicine:
  - "獣医療"
  - "veterinary medicine"
  - "動物ワクチン"
  - "animal vaccine"
  - "人獣共通感染症"
  - "zoonosis"
  - "家畜衛生"
  - "livestock health"
  - "水産防疫"
  - "aquaculture disease prevention"
