# 医学系免疫学キーワード
basic_immunology:
  - "免疫"
  - "immunology" 
  - "immunity"
  - "immune system"
  - "自然免疫"
  - "innate immunity"
  - "獲得免疫"
  - "adaptive immunity"

cells_and_molecules:
  - "T細胞"
  - "B細胞"
  - "樹状細胞"
  - "dendritic cell"
  - "マクロファージ"
  - "macrophage"
  - "NK細胞"
  - "natural killer"
  - "抗体"
  - "antibody"
  - "抗原"
  - "antigen"
  - "サイトカイン"
  - "cytokine"

advanced_research:
  - "免疫チェックポイント"
  - "immune checkpoint"
  - "CAR-T細胞"
  - "CAR-T cell therapy"
  - "単クローン抗体"
  - "monoclonal antibody"
  - "オートファジー"
  - "autophagy"

diseases_and_therapy:
  - "がん免疫"
  - "cancer immunology"
  - "免疫療法"
  - "immunotherapy"
  - "アレルギー"
  - "allergy"
  - "自己免疫"
  - "autoimmune"
  - "ワクチン"
  - "vaccine"
  - "感染症"
  - "infectious disease"
